### ISSUE TITLE
Basic Tasks

### ISSUE THREAD

**Issue by Wolverin-e** [Wolverin-e/Votechain#2]
# **TO-DO**
- [x] change DB api for normal users.
- [x] add redux in online-version
- [x] change CSS in online-version for details tab
- [x] make api calls for retriving candidates and their info in online-version
- [x] Add receipt inspector in DB api for admin side
- [x] Make admin auth connected to database
- [x] connect error handler of fetchers on admin side
- [x] reduce contract calls on client side DB api
